
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class CatlogPrint extends javax.swing.JFrame {

    /**
     * Creates new form CatlogPrint
     */
    String CatLog="_#___________________________________________________________#_"
              + "\n\t\t     AADARSH DIGITAL, Jamner City"
                + "\n\t\t     Jagannath Market, Jamner\n"
            + "\t  Prop : Sagar Mali   mobile: 8390348154 (WhatsApp)"
            + "\n\t\t\t Date: "+new Date() 
            + "\n_#___________________________________________________________#_"
           
            + "\n\t\t          Catlog"
            + "\n\t\t         ~~~~~~~~";
    public CatlogPrint() {
        initComponents();
        setIcon();
         textArea_txt.setBackground(new java.awt.Color(0, 0, 0, 1));
        jScrollPane1.getViewport().setOpaque(false);
        
    }
    
    public CatlogPrint(String a, String b, String c, String d){
            initComponents();
        setIcon();
        String CheckingCatlog="\n\tStarting Date\t\t"+a
                + "\n\tEnding Date\t\t"+b
                + "\n\tTotal Amount Count\t\t"+c
                + "\n\tTotal Amount Collection\t\t"+d;
         textArea_txt.setBackground(new java.awt.Color(0, 0, 0, 1));
        jScrollPane1.getViewport().setOpaque(false);
        //textArea_txt.setText(CatLog + CheckingCatlog);
        if("".equals(a) && "".equals(b) && "".equals(c) && "".equals(d)){
              textArea_txt.setText(CatLog);
              p_break.setForeground(Color.red);
            print_button.setEnabled(false);
        }
        else{
            textArea_txt.setText(CatLog + CheckingCatlog);
             p_break.setEnabled(false);
        }
    }
 public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_iOS_Photos_48px.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_txt = new javax.swing.JTextArea();
        p_break = new javax.swing.JLabel();
        print_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        windows_lable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aadarsh Digital(Catlog Print)");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setAlignmentX(1.0F);
        jScrollPane1.setAlignmentY(1.0F);
        jScrollPane1.setOpaque(false);

        textArea_txt.setEditable(false);
        textArea_txt.setColumns(20);
        textArea_txt.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        textArea_txt.setRows(5);
        textArea_txt.setAlignmentX(1.0F);
        textArea_txt.setAlignmentY(1.0F);
        textArea_txt.setOpaque(false);
        jScrollPane1.setViewportView(textArea_txt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 550, 390));

        p_break.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        p_break.setForeground(new java.awt.Color(255, 255, 255));
        p_break.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_break.setText("Printing break");
        p_break.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(p_break, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 100, -1));

        print_button.setFont(new java.awt.Font("Book Antiqua", 0, 16)); // NOI18N
        print_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Google_Cloud_Print_35px.png"))); // NOI18N
        print_button.setText("Print");
        print_button.setBorder(null);
        print_button.setBorderPainted(false);
        print_button.setOpaque(false);
        print_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(print_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Aadarsh Digital Catlog");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, -1));

        windows_lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/906883.png"))); // NOI18N
        getContentPane().add(windows_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void print_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_buttonActionPerformed
        /* try {
            /*        // TODO add your handling code here:

            print_txt_bill.append("GST No: 27AXPPC6230Q1ZY"
                + "\n\t\t   \tSHREE ENTERPRISES"
                + "\n---------------------------------------------------------------------"
                + "\n\t  SHASHERI NAGAR, JAMNER, Jalgoan, MAHARASTRA, 424206"
                + "\n\t  Mob:(+91) 7507725791, email: amolchavan772@gmail.com"
                + "\n");*/
            /*
            + "\n---------------------------------------------------------------------"
            + "\n\t  SHASHERI NAGAR, JAMNER, Jalgoan, MAHARASTRA, 424206"
            + "\n\t  Mob:(+91) 7507725791, email: amolchavan772@gmail.com"
            + "\n---------------------------------------------------------------------"
            */

            /*textArea_txt.append("\t\tFEDERAL XEROX, Jamner City"
                + "\t\tProp : Sagar Mali"
                + "\t\tJagannath Market"
                + "\t\t----------------------------------");

            textArea_txt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Main_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }*/

        try
        {
            boolean complete = textArea_txt.print();
            
            if(complete)
            {
                Toolkit.getDefaultToolkit().beep();

                JOptionPane.showMessageDialog(null, "Printing Done !","information",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Printing Cancel !","Printer",JOptionPane.ERROR_MESSAGE);
            }

        }
        //new Main_Acti().setVisiable(true);
        catch(HeadlessException | PrinterException e)
        {
            //JOptionPane.showMessageDialog(null, e);
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Printing Cancel !","Printer",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_print_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatlogPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatlogPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatlogPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatlogPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatlogPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel p_break;
    private javax.swing.JButton print_button;
    private javax.swing.JTextArea textArea_txt;
    private javax.swing.JLabel windows_lable;
    // End of variables declaration//GEN-END:variables
}
