
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
         setIcon();
        user_txt.setBackground(new java.awt.Color(0,0,0,1));
        old_pass.setBackground(new java.awt.Color(0,0,0,1));
        new_pass.setBackground(new java.awt.Color(0,0,0,1));
        re_enter_pass.setBackground(new java.awt.Color(0,0,0,1));
    }
     public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_iOS_Photos_48px.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        close_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        Check_pass = new javax.swing.JCheckBox();
        user_txt = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        re_enter_pass = new javax.swing.JPasswordField();
        jSeparator17 = new javax.swing.JSeparator();
        new_pass = new javax.swing.JPasswordField();
        jSeparator18 = new javax.swing.JSeparator();
        old_pass = new javax.swing.JPasswordField();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aadarsh Digital (Change Password)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("Re-Enter");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setText("New Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setText("Old Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setText("User Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, -1, 30));

        close_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        close_btn.setText("Close");
        close_btn.setBorder(null);
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        getContentPane().add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 90, 30));

        save_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Opened Folder_48px.png"))); // NOI18N
        save_btn.setText("Save");
        save_btn.setBorder(null);
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 520, 110, 30));

        Check_pass.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Check_pass.setForeground(new java.awt.Color(255, 255, 255));
        Check_pass.setText("Show Password");
        Check_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_passActionPerformed(evt);
            }
        });
        getContentPane().add(Check_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, 220, 30));

        user_txt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        user_txt.setForeground(new java.awt.Color(255, 255, 255));
        user_txt.setBorder(null);
        user_txt.setOpaque(false);
        user_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                user_txtKeyTyped(evt);
            }
        });
        getContentPane().add(user_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 290, 20));

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 290, 10));

        re_enter_pass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        re_enter_pass.setForeground(new java.awt.Color(255, 255, 255));
        re_enter_pass.setBorder(null);
        re_enter_pass.setOpaque(false);
        getContentPane().add(re_enter_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, 290, 20));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 290, 10));

        new_pass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        new_pass.setForeground(new java.awt.Color(255, 255, 255));
        new_pass.setBorder(null);
        new_pass.setOpaque(false);
        getContentPane().add(new_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, 290, 20));

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 370, 290, 10));

        old_pass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        old_pass.setForeground(new java.awt.Color(255, 255, 255));
        old_pass.setBorder(null);
        old_pass.setOpaque(false);
        getContentPane().add(old_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, 290, 20));

        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 290, 10));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Update Your Password");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/906883.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        new Main_Acti().setVisible(true);
        dispose();
    }//GEN-LAST:event_close_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        String Epass=old_pass.getText();
        String Npass=new_pass.getText();
        String Cpass=re_enter_pass.getText();
        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();
        try
        {
            if(user_txt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Fill UserName !");
            }
            else if(old_pass.getText().equals("") )
            {
                JOptionPane.showMessageDialog(null, "Fill Exist Password and UserName !");

            }
            else  if(new_pass.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Fill New Password Password !");

            }
            else  if(re_enter_pass.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Fill Conform Password !");

            }
            else
            {
                //String a=rs.getString("user_id");
                if(new_pass.getText().equals(re_enter_pass.getText()))
                {

                    String sql="update auth set Pass='"+Cpass+"' where Name='"+user_txt.getText()+"'";

                    pst=conn.prepareStatement(sql);
                    int C=JOptionPane.showConfirmDialog(null,"Do you want to Really Save?","Conform Save",JOptionPane.YES_NO_OPTION);
                    if(C==0)
                    {
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Update Successfully");
                        user_txt.setText("");
                        old_pass.setText("");
                        new_pass.setText("");
                        re_enter_pass.setText("");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Password not Match");
                }
            }
        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        finally
        {
            try
            {
                if(rs!=null)
                {
                    rs.close();

                }
                if(pst!=null)
                {
                    pst.close();
                }
                if(conn!=null)
                {
                    conn.close();
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void Check_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_passActionPerformed
        // TODO add your handling code here:
        if(Check_pass.isSelected())
        {
            old_pass.setEchoChar((char)0);
            new_pass.setEchoChar((char)0);
            re_enter_pass.setEchoChar((char)0);
        }
        else
        {
            old_pass.setEchoChar('*');
            new_pass.setEchoChar('*');
            re_enter_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_Check_passActionPerformed

    private void user_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_txtKeyTyped
        // TODO add your handling code here:
        /* char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }*/
    }//GEN-LAST:event_user_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check_pass;
    private javax.swing.JButton close_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JPasswordField new_pass;
    private javax.swing.JPasswordField old_pass;
    private javax.swing.JPasswordField re_enter_pass;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField user_txt;
    // End of variables declaration//GEN-END:variables
}
