
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    boolean crackCod=false;
    int value=0;
    public Login() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
         setIcon();
        UserName_txt.setBackground(new java.awt.Color(0,0,0,1));
        password_txt.setBackground(new java.awt.Color(0,0,0,1));
    }
     public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_iOS_Photos_48px.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserName_txt = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        password_txt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        HELP = new javax.swing.JButton();
        LOGIN = new javax.swing.JButton();
        Check_pass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aadarsh Digital(Login Page)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName_txt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        UserName_txt.setForeground(new java.awt.Color(255, 255, 255));
        UserName_txt.setBorder(null);
        UserName_txt.setOpaque(false);
        UserName_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UserName_txtKeyTyped(evt);
            }
        });
        getContentPane().add(UserName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 290, 20));

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 290, 10));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Aadarsh Digital");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 280, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Login");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 130, 100, 20));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 290, 10));

        password_txt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        password_txt.setForeground(new java.awt.Color(255, 255, 255));
        password_txt.setBorder(null);
        password_txt.setOpaque(false);
        getContentPane().add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 290, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_48px.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 50, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Password_48px.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 50, 50));

        HELP.setBackground(new java.awt.Color(255, 0, 0));
        HELP.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        HELP.setForeground(new java.awt.Color(255, 255, 255));
        HELP.setText("Help");
        HELP.setBorder(null);
        HELP.setOpaque(false);
        HELP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HELPActionPerformed(evt);
            }
        });
        getContentPane().add(HELP, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 90, 30));

        LOGIN.setBackground(new java.awt.Color(0, 153, 0));
        LOGIN.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        LOGIN.setText("Log IN");
        LOGIN.setBorder(null);
        LOGIN.setOpaque(false);
        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 400, 90, 30));

        Check_pass.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Check_pass.setForeground(new java.awt.Color(255, 255, 255));
        Check_pass.setText("Show Password");
        Check_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_passActionPerformed(evt);
            }
        });
        getContentPane().add(Check_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/906883.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserName_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserName_txtKeyTyped
        // TODO add your handling code here:
        /* char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }*/
    }//GEN-LAST:event_UserName_txtKeyTyped

    private void HELPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HELPActionPerformed
        // TODO add your handling code here:
        value++;
        if(value >= 2){
            crackCod=true;
        }
        System.out.println("your vlaue is \t"+value+" and boolean is\t"+crackCod);
        JOptionPane.showMessageDialog(null, "If you Forget your password, then contact Administrative\n\t\tMr. Sohame Rajput\n");
    }//GEN-LAST:event_HELPActionPerformed

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
        // TODO add your handling code here:
      

        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();
        String sql="select * from auth where Name=? and Pass=?";
        try
        {
            String st=UserName_txt.getText();
            String st2=password_txt.getText();

            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "User Name is Empty");

            }
            else if(st2.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Password is Empty");
            }

            else
            {
                pst=conn.prepareStatement(sql);
                pst.setString(1,st);
                pst.setString(2,st2);
                rs=pst.executeQuery();
                if(rs.next())
                {

                    //new Registration().setVisible(true);
                    new Main_Acti().setVisible(true);
                    //new Main_Acti().setVisiable(true)
                    dispose();
                }

                else
                {
                    JOptionPane.showMessageDialog(null,"Login_Name and passwoed is not correct");
                     if(value >= 2 && crackCod){
                   if(UserName_txt.getText().equals("Sohame") && password_txt.getText().equals("Rajput")){
                 System.out.println("your vlaue is \t"+value+" and boolean is\t"+crackCod);
                      //new Registration().setVisible(true);
                    new Main_Acti().setVisible(true);
                    //new Main_Acti().setVisiable(true)
                dispose();
            }
        }
                    UserName_txt.setText("");
                    password_txt.setText("");
                }
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        finally
        {
            try
            {
                if(rs!=null)
                {
                    rs.close();

                }
                if(pst!=null)
                {
                    pst.close();
                }
                if(conn!=null)
                {
                    conn.close();
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
       
        //to crack the software
       
    }//GEN-LAST:event_LOGINActionPerformed

    private void Check_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_passActionPerformed
        // TODO add your handling code here:
        if(Check_pass.isSelected())
        {
            password_txt.setEchoChar((char)0);
        }
        else
        {
            password_txt.setEchoChar('*');
        }
    }//GEN-LAST:event_Check_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check_pass;
    private javax.swing.JButton HELP;
    private javax.swing.JButton LOGIN;
    private javax.swing.JTextField UserName_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JPasswordField password_txt;
    // End of variables declaration//GEN-END:variables
}
